plugins {
    id 'com.android.application'
}

android {
    namespace 'com.whisper.library'
    compileSdk 35

    defaultConfig {
        applicationId 'com.whisper.wowlibrary'
        minSdk 21
        targetSdk 30
        versionCode 3
        versionName '1.0.2'
    }

    buildTypes {
        debug {
            debuggable true
            minifyEnabled false
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
